CI fixes
thoth-tech/doubtfire-api pull request #19
Opened 2024-03-26 16:57 UTC by ublefo

Please merge #18 first. This took me _weeks_ to figure out and test, now everything is finally working as they should. 

Improvements made:
1. Implemented container caching to bring turnaround time from [52 minutes](https://github.com/doubtfire-lms/doubtfire-api/actions/runs/8396126610/job/22996854649) to [16 minutes](https://github.com/ublefo/doubtfire-api/actions/runs/8439026003/job/23112641848).
2. Set up redis in the workflow and make sure sidekiq is configured to use the correct URL from the environment if it's present.
3. Upgrade actions/checkout to v4 to get rid of the deprecation warning.
4. Install `ruby-lsp` in the development environment for the corresponding vscode extension, which is currently already installed in the devcontainer but completely useless due to the gem being missing.
5. Implement better error reporting in `database_populator.rb` to report the error messages when there's something wrong with the test data. Troubleshooting test db initialization issues should be much easier now.

Instruction for reviewers: just check the CI workflows below and they should be all passing now.

2024-03-26 21:45 UTC, maddernd commented
Have these changes been tested on Mac and Windows?

2024-03-27 03:20 UTC, satikaj commented
Unit tests work on Mac. I tested the CI GitHub actions workflow on my fork too for these commits and they all succeed now. The implemented cache functionality also makes it run faster on the second time around.

2024-03-27 08:43 UTC, macite requested changes
This looks very good. If we can get that one new environment variable explained alongside the other environment variables in the README I think... then it should be good to merge.

2024-03-27 08:43 UTC, macite commented on config/initializers/sidekiq.rb
> +  config.redis = { url: ENV.fetch('DF_REDIS_SIDEKIQ_URL', 'redis://localhost:6379/1') }
Add this new environment variable to the documentation so that it is captured there - this way we have all of the expected environment variables captured in the one place.

2024-03-27 08:44 UTC, macite commented
Once this is addressed you can make the PR to the main repo.

2024-03-28 02:02 UTC, maddernd commented
This one looks good now please make upstream.

2024-03-28 23:22 UTC, closed without merging

2024-03-28 23:22 UTC, ublefo commented
Pull request opened upstream: https://github.com/doubtfire-lms/doubtfire-api/pull/434